AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CComplete Serverless backend - DynamoDB tables + Lambda functions + API Gateway + cognito

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    MemorySize: 128
    CodeUri: ./lambda_functions/

Parameters:
  Environment:
    Type: String
    Default: dev
        
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "crs-user-pool-${Environment}"
      Schema:
        - Name: role
          AttributeDataType: String
          Mutable: true
          Required: false     


  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "crs-client-${Environment}"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false 
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH             

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "CRS-Users-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: GSI_PHONE_PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI_PHONE
          KeySchema:
            - AttributeName: GSI_PHONE_PK
              KeyType: HASH
          Projection:
            ProjectionType: ALL
            
  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "CRS-${Environment}"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
           CognitoAuthorizer:
             UserPoolArn: !GetAtt CognitoUserPool.Arn
             Identity:
               Header: Authorization
                        
  CustomerSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "customer_signup-${Environment}"
      Handler: Auth.customer_signup.lambda_handler
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:SignUp
            Resource: "*"
      Events:
        SignupApi:
          Type: Api
          Properties:
            Path: /customer_signup
            RestApiId: !Ref ServerlessApi
            Method: post